[build]
  # Optional: You can specify any build setup here, such as installing dependencies
  # e.g., using python 3
  setup = "python3, gcc"

[install]
  command = "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"

[start]
  command = "uvicorn app:app --host 0.0.0.0 --port 8000"
