[build]
# Optional build setup
setup = "python3, gcc"

[install]
# Install dependencies in virtual environment
command = "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"

[start]
# The command to start the app
command = "uvicorn app:app --host 0.0.0.0 --port 8000"
